#ifndef __ScoreHistogram__
#define __ScoreHistogram__

#include "stdafx.h"

/**
@file
Subclass of TScoreHistogram, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

/** Implementing TScoreHistogram */
class ScoreHistogram : public TScoreHistogram
{
	public:
		/** Constructor */
		ScoreHistogram( wxWindow* parent );
        void ClearHistogram();
        void setUseKataGo(bool use_KataGo);
        bool getUseKataGo();
	//// end generated class members
    private:
        void doNewScore(wxCommandEvent& event);

        static std::vector<std::tuple<int, float, float, float>> m_scores;
        bool m_use_KataGo;
    friend class TScorePanel;

};

#endif // __ScoreHistogram__
